drop table businessunit;
drop table designation;
drop table emergencycontacts;
drop table employee;
drop table employeeprojectallocation;
drop table holidays;
drop table practise;
drop table projects;
drop table tasks;
drop table timesheetcomments;
drop table timesheets;
drop table submissions;
drop table logs;
drop table projectsubmissions;
drop table permissioncode;
drop table userpermissions;


create table businessunit (
    id serial primary key not null,
    name varchar(100),
    addedby int,
    addeddate date
);


create table designation (
    id serial primary key not null,
    name varchar(100)
);


create table emergencycontacts (
    id serial primary key not null,
    name varchar(150),
    relationship varchar(100),
    isprimary boolean,
    address text,
    empid int
);


create table employee (
    id serial primary key not null,
    firstname varchar(150),
    lastname varchar(150),
    empid varchar(150) unique,
    password varchar(150),
    personalemailid varchar(150),
    emailid varchar(150),
    designation varchar(150),
    reportingmanger int,
    practise character varying(150),
    practiserole character varying(150),
    role character varying(150),
    jobfamily character varying(150),
    jobgrade character varying(150),
    department character varying(150),
    doj date,
    location character varying(150),
    address text,
    dob date,
    addedby character varying(150),
    addeddate date,
    lastloggeddate timestamp with time zone,
    logintime timestamp with time zone
);



CREATE TABLE employeeprojectallocation
(
    id serial primary key not null,
    empid character varying(100),
    projectid character varying(100),
    startdate date,
    enddate date,
    isbillable character varying(20),
    role character varying(100),
    allocationtype character varying(100),
    reportingto varchar(10),
    subteam varchar(50)
);


CREATE TABLE holidays
(
    id serial primary key not null,
    name character varying(100) ,
    holidaydate date,
    isoptional character varying(20)
);



CREATE TABLE practise
(
    id serial primary key not null,
    name character varying(100)
);



CREATE TABLE projects
(
    id serial primary key not null,
    name character varying(100) unique,
    businessid integer,
    expectedstartdate date,
    expectedenddate date,
    actualstartdate date,
    actualenddate date
);


CREATE TABLE tasks
(
    id serial primary key not null,
    name character varying(100) ,
    expectedwork character varying(20)
);


CREATE TABLE timesheetcomments
(
    id serial primary key not null,
    comment text ,
    commentby numeric,
    commentdate date,
    viewcount numeric,
    timesheetid numeric
);


CREATE TABLE timesheets
(
    id serial primary key not null,
    empid character varying(100) ,
    projectid character varying(100) ,
    taskid character varying(100) ,
    loggedhours numeric,
    isapproved boolean,
    declinedcount numeric,
    comment text ,
    isholiday boolean,
    onleave boolean,
    comboff boolean,
    timesheetdate timestamp with time zone
);



create table submissions (
	id serial primary key,
    empid varchar(150),
    pid	numeric,
    submonth numeric,
    subyear numeric,
    subcount numeric,
    submittedon timestamp with time zone
);

create table logs (
	id serial primary key,
    updateby varchar(100),
    updateddate timestamp with time zone,
    tablename varchar(100),
    actiontype varchar(10),
    updateddata text,
   	updatinginfo text
);

create table projectsubmissions (
    id serial primary key,
    pid numeric,
    submonth numeric,
    subyear numeric,
    submittedon timestamp with time zone,
    submittedby varchar(50)
);


create table permissioncode(
	id serial primary key,
    name varchar(50),
    code varchar(10),
    description text
);
create table userpermissions (
	id serial primary key,
    code varchar(10),
    empid varchar(50)
);



-- To Add root user in DB
-- insert into employee (firstname, lastname, empid, password, emailid, reportingmanger, role)
-- values ('root', 'root', '0', 'root', 'mtottimpudi', 0, 'admin');
insert into employee (empid, firstname, lastname, doj, jobgrade, designation, practise, department, reportingmanger, emailid, password) values
( '2', 'Hari Babu', 'Madduluri', '17-Nov-03', 'C1', 'Associate Manager - SW', 'Java Practice', 'CSC', 1, 'hmadduluri@evoketechnologies.com', '12345' ),
( '12', 'Dayanand', 'Lingampally', '20-Mar-04', 'C1', 'Associate Manager - SW', 'Oracle Practice', 'Clopay', 738, 'dlingampally@evoketechnologies.com', '12345' ),
( '15', 'Venkata Srinivas', 'Surla', '14-Jul-04', 'B3', 'Team Lead', 'Delivery', 'CSC', 1, 'vsurla@evoketechnologies.com', '12345' ),
( '29', 'Mahesh Kumar', 'Chittimela', '21-Mar-05', 'B3', 'Technical Lead', 'BI Practice', 'CSC', 15, 'mchittimela@evoketechnologies.com', '12345' ),
( '30', 'Giridhar', 'Yerraneni', '01-Apr-05', 'B3', 'Lead - Quality Analyst', 'QA Practice', 'CSC', 134, 'gyerraneni@evoketechnologies.com', '12345' ),
( '34', 'Venugopal', 'Sunku', '05-Sep-05', 'C3', 'Senior Manager - Delivery', 'Delivery', 'CSC', 1, 'vsunku@evoketechnologies.com', '12345' ),
( '35', 'Ramanjula Reddy', 'Bijjam', '14-Nov-05', 'C2', 'Architect', 'BI Practice', 'CSC', 1, 'rbijjam@evoketechnologies.com', '12345' ),
( '42', 'Purnima', 'Edupuganti', '13-Mar-06', 'B3', 'Test Lead', 'QA Practice', 'CSC', 34, 'pvemulapalli@evoketechnologies.com', '12345' ),
( '62', 'Lohith', 'Ramanaboyina', '07-Nov-06', 'B3', 'Specialist - Quality', 'QA Practice', 'Clopay', 156, 'lramanaboyina@evoketechnologies.com', '12345' ),
( '65', 'Rakesh', 'Chamarti', '11-Dec-06', 'B3', 'Senior Analyst - Software Development', 'Java Practice', 'CSC', 2, 'rchamarti@evoketechnologies.com', '12345' ),
( '67', 'Ramesh', 'Guddati', '08-Jan-07', 'C1', 'Associate Solution Consultant - Database', 'Microsoft Practice', 'CSC', 15, 'rguddatti@evoketechnologies.com', '12345' ),
( '84', 'Rajeev', 'Vemulapalli', '11-Jul-07', 'B3', 'Lead - Data Entry', 'BPO', 'CSC', 1, 'rvemulapalli@evoketechnologies.com', '12345' ),
( '98', 'Kiran', 'Ponaganti', '24-Dec-07', 'B2', 'Senior Developer - DB', 'BI Practice', 'CSC', 134, 'kponaganti@evoketechnologies.com', '12345' ),
( '106', 'Sriram', 'Madala', '11-Feb-08', 'B3', 'Team Lead', 'Java Practice', 'CSC', 2, 'smadala@evoketechnologies.com', '12345' ),
( '108', 'Anil Raja Maddali', 'Venkata Naga', '21-Apr-08', 'B3', 'Technical Lead', 'Java Practice', 'CSC', 212, 'amaddali@evoketechnologies.com', '12345' ),
( '109', 'Kiran Chowdary', 'Uppu', '13-Jan-07', 'C1', 'Associate Manager - HR', 'HR', 'Recruitment', 1019, 'kuppu@evoketechnologies.com', '12345' ),
( '128', 'Shiva Kumar', 'Damara Golla', '13-Nov-08', 'B3', 'Senior Analyst - Software Development', 'Java Practice', 'CSC', 134, 'sdamaragolla@evoketechnologies.com', '12345' ),
( '134', 'Bala Gangadhara', 'Tilak Mamidipalli', '12-Feb-09', 'C2', 'Delivery Manager', 'Java Practice', 'CSC', 34, 'bmamidipalli@evoketechnologies.com', '12345' ),
( '142', 'Saroj Babu', 'Paladugu', '18-Jun-09', 'C1', 'Associate Solution Consultant', 'Java Practice', 'CSC', 1, 'spaladugu@evoketechnologies.com', '12345' ),
( '144', 'Sarada Charan', 'Voruganti', '07-Jan-09', 'B3', 'Technical Lead', 'Microsoft Practice', 'Clopay', 175, 'cvoruganti@evoketechnologies.com', '12345' ),
( '146', 'Sesi Raj', 'Nunekoppula', '10-Aug-09', 'C1', 'Associate Manager - QA', 'QA Practice', 'CSC', 880, 'snunekoppula@evoketechnologies.com', '12345' ),
( '148', 'Kavitha', 'Gorantla', '25-Jul-09', 'A2', 'Data Entry Associate', 'BPO', 'CSC', 84, 'kgorantla@evoketechnologies.com', '12345' ),
( '151', 'Arun Kumar', 'Singh', '11-Nov-09', 'C1', 'Project Manager', 'Java Practice', 'CSC', 1039, 'asingh1@evoketechnologies.com', '12345' ),
( '156', 'Sanketh', 'Kulkarni', '20-Jan-10', 'C1', 'Project Manager', 'QA Practice', 'Clopay', 521, 'skulkarni@evoketechnologies.com', '12345' ),
( '162', 'Uday Kumar', 'Gottimukkala', '15-Feb-10', 'C2', 'Business Development Manager', 'Sales', 'Inside Sales', 880, 'ukumar@evoketechnologies.com', '12345' ),
( '163', 'Venkateshwarlu', 'Pidamarthy', '15-Feb-10', 'A2', 'Data Entry Associate', 'QA Practice', 'Ritas', 507, 'vpidamarthy@evoketechnologies.com', '12345' ),
( '165', 'Rudra NVN', 'Murthy', '01-Mar-10', 'B2', 'Senior System Administrator', 'Support Staff', 'Clopay', 207, 'rmurthy@evoketechnologies.com', '12345' ),
( '168', 'Murali', 'Anugutala', '02-Mar-10', 'B3', 'Technical Lead', 'Microsoft Practice', 'Clopay', 521, 'manugutala@evoketechnologies.com', '12345' ),
( '175', 'Venkata Sivannarayana', 'Chalavadi', '26-Apr-10', 'B3', 'Team Lead', 'Microsoft Practice', 'Clopay', 521, 'schalavadi@evoketechnologies.com', '12345' ),
( '177', 'Laxma Reddy', 'Patlolla', '02-May-10', 'C2', 'Business Development Manager', 'Sales', 'Inside Sales', 348, 'lreddy@evoketechnologies.com', '12345' ),          
( '181', 'Sankara Reddy', 'Kadiveti', '31-May-10', 'B2', 'Senior Software Engineer', 'Microsoft Practice', 'Clopay', 168, 'skadiveti@evoketechnologies.com', '12345' ),
( '184', 'Bapaiah Chowdary', 'Koya', '16-Jun-10', 'B3', 'Lead - Admin & Facilities', 'Support Staff', 'Evoke', 1019, 'bkoya@evoketechnologies.com', '12345' ),
( '185', 'Mohammed', 'Irfan', '01-Jul-10', 'C1', 'Associate Manager -Accounts', 'Finance', 'Accounts', 1, 'imohammed@evoketechnologies.com', '12345' ),
( '186', 'Prasanna Kumar', 'Prattipati', '01-Jul-10', 'B3', 'Senior Analyst - Performance Engineer', 'QA Practice', 'CSC', 503, 'pprattipati@evoketechnologies.com', '12345' ),
( '190', 'Sunil', 'Lingampally', '19-Aug-10', 'B2', 'Senior Software Test Engineer', 'QA Practice', 'Clopay', 156, 'slingampally@evoketechnologies.com', '12345' ),
( '198', 'Manikanth', 'Thammareddy', '11-Oct-10', 'C2', 'Architect', 'Big Data Practice', 'Java Practice', 880, 'mthammareddy@evoketechnologies.com', '12345' ),
( '201', 'Sravan Kumar', 'Panangipalli', '25-Oct-10', 'B3', 'Technical Lead', 'Java Practice', 'Prime Tech', 1074, 'spanangipalli@evoketechnologies.com', '12345' ),
( '207', 'Raghavendra Rao', 'Addanki', '01-Dec-10', 'D1, Level 1', 'Associate Director - IT', 'IT & Infrastructure', 'IT & Infrastructure', 1, 'raddanki@evoketechnologies.com', '12345' ),
( '210', 'Sree Rama Anil', 'Borusu', '03-Dec-10', 'B3', 'Technical Lead', 'Microsoft Practice', 'Clopay', 521, 'sborusu@evoketechnologies.com', '12345' ),
( '212', 'Mohan Babu', 'Chikkala', '01-Jan-11', 'C2', 'Delivery Manager', 'Delivery', 'CSC', 1039, 'mchikkala@evoketechnologies.com', '12345' ),
( '215', 'Jithendar', 'Goud Vanga', '23-Dec-10', 'C1', 'Associate Manager - HR', 'HR', 'Recruitment', 1019, 'jvanga@evoketechnologies.com', '12345' ),
( '217', 'Umesh Krishna', 'Shivakanth', '30-Dec-10', 'B2', 'Senior Technical Associate', 'Microsoft Practice', 'CSC', 483, 'ushivakanth@evoketechnologies.com', '12345' ),
( '222', 'Satyanarayana Reddy', 'Kolli', '13-Jan-11', 'C1', 'Associate Manager - IT', 'IT & Infrastructure', 'IT & Infrastructure', 207, 'skolli@evoketechnologies.com', '12345' ),
( '234', 'Kamal Kumar', 'Viswanadhapalli', '26-Jan-11', 'B3', 'Technical Lead', 'Java Practice', 'CSC', 1039, 'kviswanadhapalli@evoketechnologies.com', '12345' ),
( '246', 'Venkatesh', 'Ganji', '06-Feb-11', 'B3', 'Lead-Business Analyst', 'QA Practice', 'Clopay', 521, 'vganji@evoketechnologies.com', '12345' ),
( '247', 'Kiran Kumar', 'Kota', '07-Feb-11', 'B2', 'Senior Technical Associate', 'Microsoft Practice', 'CSC', 483, 'kkota@evoketechnologies.com', '12345' ),
( '254', 'Ravitheja', 'Veguru', '24-Feb-11', 'B2', 'Senior Software Engineer', 'QA Practice', 'Clopay', 1040, 'rveguru@evoketechnologies.com', '12345' ),
( '268', 'Prabhakar', 'Tonigandla', '25-Mar-11', 'C1', 'Associate Solution Consultant', 'Microsoft Practice', 'CSC', 787, 'ptonigandla@evoketechnologies.com', '12345' ),
( '275', 'Surna', 'Swetha', '13-Apr-11', 'B2', 'Senior Associate - Admin & Facilities', 'Support Staff', 'Evoke', 1058, 'ssurna@evoketechnologies.com', '12345' ),
( '279', 'VijayaKumar', 'Bandreddy', '21-Apr-11', 'B3', 'Technical Lead', 'Microsoft Practice', 'Axalta', 1009, 'vbandreddy@evoketechnologies.com', '12345' ),
( '280', 'Lalitha', 'Mamillapalli', '25-Apr-11', 'B2', 'Senior Software Engineer', 'Oracle Practice', 'Clopay', 738, 'lmamillapalli@evoketechnologies.com', '12345' ),
( '284', 'Nagaraju', 'Thandra', '28-Apr-11', 'B2', 'Senior Executive-Admin & Facilities', 'Support Staff', 'Evoke', 1019, 'nthandra@evoketechnologies.com', '12345' ),
( '298', 'Pratyusha', 'Surapaneni', '02-Jun-11', 'B2', 'Senior Software Test Engineer', 'QA Practice', 'Clopay', 521, 'psurapaneni@evoketechnologies.com', '12345' ),
( '310', 'Bhaskar', 'Manepally', '04-Jul-11', 'B2', 'Senior Software Engineer', 'Open Source Practice', 'CSC', 2, 'bmanepally@evoketechnologies.com', '12345' ),
( '318', 'Jyothirmai', 'Gudivada', '21-Jul-11', 'B2', 'Senior Software Engineer', 'Microsoft Practice', 'Microsoft Practice', 546, 'jgudivada@evoketechnologies.com', '12345' ),
( '320', 'Subrahmanyeswara Dasu', 'Kodali', '25-Jul-11', 'B2', 'Senior Software Engineer', 'Open Source Practice', 'CSC', 679, 'skodali@evoketechnologies.com', '12345' ),
( '337', 'Devaraj', 'Busa', '25-Aug-11', 'B2', 'Senior Software Engineer', 'BI Practice', 'CSC', 29, 'dbusa@evoketechnologies.com', '12345' ),
( '348', 'Hari Prasad', 'Alla', '03-Oct-11', 'C2', 'Technical Architect', 'Java Practice', 'Java Practice', 880, 'halla@evoketechnologies.com', '12345' ),
( '353', 'Mustaq Basha', 'Shaik', '11-Oct-11', 'B3', 'Technical Lead - UI', 'Open Source Practice', 'CSC', 2, 'mshaik@evoketechnologies.com', '12345' ),
( '359', 'Chandrasekhar Rao', 'Reddipalli', '03-Nov-11', 'B3', 'Team Lead', 'QA Practice', 'CSC', 787, 'creddipalli@evoketechnologies.com', '12345' ),
( '370', 'Leela Manohar Chowdary', 'Yenuganti', '02-Jan-12', 'B2', 'Senior System Administrator', 'IT & Infrastructure', 'IT & Infrastructure', 207, 'lyenuganti@evoketechnologies.com', '12345' ),
( '371', 'Venkata Sandeep Reddy', 'Bandi', '02-Jan-12', 'B2', 'Senior Technical Associate', 'Java Practice', 'CSC', 2, 'vbandi@evoketechnologies.com', '12345' ),
( '388', 'Ramamohan', 'Annamaneni', '12-Mar-12', 'B3', 'Team Lead', 'Oracle Practice', 'CSC', 446, 'rannamaneni@evoketechnologies.com', '12345' ),
( '397', 'Sandhya Rani', 'Bandarlanka', '02-Apr-12', 'A2', 'Data Entry Associate', 'BPO', 'CSC', 84, 'sbandarlanka@evoketechnologies.com', '12345' ),
( '400', 'Fathima', 'Sulthana', '09-Apr-12', 'B3', 'Technical Lead', 'Mobility Practice', 'Axalta', 756, 'fsulthana@evoketechnologies.com', '12345' ),
( '402', 'Vijaya Sundar', 'Chedalavada', '11-Apr-12', 'A2', 'Data Entry Associate', 'QA Practice', 'CSC', 67, 'vchedalavada@evoketechnologies.com', '12345' ),
( '403', 'Naveen', 'Varadaraju', '11-Apr-12', 'B2', 'Senior Software Test Engineer', 'QA Practice', 'CSC', 483, 'nvaradaraju@evoketechnologies.com', '12345' ),
( '404', 'Vamshi', 'Baswapuram', '13-Apr-12', 'B1', 'Business Development Executive', 'Sales', 'Inside Sales', 880, 'vbasawapuram@evoketechnologies.com', '12345' ),
( '405', 'Narendra Kumar', 'Pinneti', '18-Apr-12', 'B1', 'Data Entry Associate', 'BPO', 'CSC', 84, 'npinneti@evoketechnologies.com', '12345' ),
( '411', 'Lakshmi Narayana Reddy', 'Rangareddygari', '16-May-12', 'B1', 'Technical Associate', 'BI Practice', 'CSC', 134, 'lrangareddygari@evoketechnologies.com', '12345' ),
( '417', 'Lalitha Devi', 'Mantena', '04-Jun-12', 'A2', 'Data Entry Associate', 'BPO', 'CSC', 84, 'lmantena@evoketechnologies.com', '12345' ),
( '420', 'Venkata Kartheek', 'Neerukattu', '11-Jun-12', 'C1', 'Associate Manager', 'Open Source Practice', 'Ritas', 880, 'vneerukattu@evoketechnologies.com', '12345' ),
( '423', 'Venkata Laxmi Narasimha Rao', 'Kalakota', '13-Jun-12', 'B3', 'Technical Lead', 'Open Source Practice', 'Ritas', 420, 'nkalakota@evoketechnologies.com', '12345' ),
( '428', 'Krishnachary', 'Birudoju', '29-Jun-12', 'B2', 'Senior Software Engineer', 'Mobility Practice', 'Mobility Practice', 1119, 'kbirudoju@evoketechnologies.com', '12345' ),
( '429', 'Prem kumar', 'Pollapalli', '02-Jul-12', 'B1', 'Business Development Executive', 'Sales', 'Inside Sales', 880, 'ppollapalli@evoketechnologies.com', '12345' ),
( '432', 'Siva Kumar', 'Bethu', '05-Jul-12', 'B2', 'Senior Software Engineer', 'Open Source Practice', 'Dominion', 897, 'sbethu@evoketechnologies.com', '12345' ),
( '441', 'Praveen Kumar', 'Entenki', '26-Jul-12', 'A2', 'Data Entry Associate', 'BPO', 'CSC', 84, 'pentenki@evoketechnologies.com', '12345' ),
( '443', 'Naresh', 'Edupuganti', '21-Aug-12', 'C1', 'Project Manager', 'Oracle Practice', 'CSC', 738, 'nedupuganti@evoketechnologies.com', '12345' ),
( '457', 'Sravanthi', 'Marriboyina', '05-Sep-12', 'B2', 'Senior Software Test Engineer', 'QA Practice', 'Clopay', 156, 'smarriboyina@evoketechnologies.com', '12345' ),
( '461', 'Murali', 'Kankuri', '20-Sep-12', 'B3', 'Senior Analyst - SW', 'Microsoft Practice', 'Dominion', 1046, 'mkankuri@evoketechnologies.com', '12345' ),
( '463', 'Naresh Kumar', 'Malchalam', '03-Oct-12', 'A2', 'Data Entry Associate', 'BI Practice', 'CSC', 29, 'nmalchalam@evoketechnologies.com', '12345' ),
( '469', 'Hareesh', 'Parvathaneni', '17-Oct-12', 'B3', 'Technical Lead', 'Java Practice', 'CSC', 234, 'hparvathaneni@evoketechnologies.com', '12345' ),
( '470', 'Suresh', 'Nakertha            ', '17-Oct-12', 'B2', 'Senior Software Engineer', 'Microsoft Practice', 'Clopay', 1040, 'snakertha@evoketechnologies.com', '12345' ),
( '473', 'Srinivas Rao', 'Meda', '25-Oct-12', 'B3', 'Technical Lead', 'Open Source Practice', 'Clopay', 210, 'smeda@evoketechnologies.com', '12345' ),
( '476', 'Ravi', 'Attada', '06-Nov-12', 'B2', 'Senior Software Engineer', 'Microsoft Practice', 'Axalta', 279, 'rattada@evoketechnologies.com', '12345' ),
( '483', 'Rajesh', 'Swamisetty', '17-Dec-12', 'B3', 'Team Lead', 'Microsoft Practice', 'CSC', 521, 'rswamisetty@evoketechnologies.com', '12345' ),
( '484', 'Rajendra Prasad', 'Sandupatla', '21-Jan-13', 'B3', 'Senior Analyst - SW', 'Open Source Practice', 'Dominion', 897, 'rsandupatla@evoketechnologies.com', '12345' ),
( '492', 'Narayana Rao', 'Gara', '11-Feb-13', 'B2', 'Senior Technical Associate', 'Microsoft Practice', 'CSC', 483, 'ngara@evoketechnologies.com', '12345' ),
( '497', 'Bobby', 'Alla', '11-Mar-13', 'B1', 'Software Test Engineer', 'QA Practice', 'QA Practice', 880, 'balla@evoketechnologies.com', '12345' ),
( '503', 'Shirisha', 'Thorupunoori', '27-Mar-13', 'B3', 'Team Lead', 'QA Practice', 'CSC', 212, 'sthorupunoori@evoketechnologies.com', '12345' ),
( '505', 'Krishna Kumar', 'Sakinala', '01-Apr-13', 'B3', 'Specialist - Quality Analyst', 'QA Practice', 'Dominion', 546, 'ksakinala@evoketechnologies.com', '12345' ),
( '507', 'Srinivas Vinayaka', 'Kondamudi', '04-Apr-13', 'B3', 'Lead - Quality Analyst', 'QA Practice', 'Prime Tech', 1074, 'vkondamudi@evoketechnologies.com', '12345' ),
( '510', 'Prasad', 'Namala', '16-Apr-13', 'B2', 'Senior Software Engineer', 'Oracle Practice', 'Clopay', 12, 'pnamala@evoketechnologies.com', '12345' ),
( '520', 'Sateesh', 'Vykuntapu', '29-May-13', 'B2', 'Senior Software Test Engineer', 'QA Practice', 'Clopay', 521, 'svykuntapu@evoketechnologies.com', '12345' ),
( '521', 'Pratyush', 'Dash', '30-May-13', 'D1, Level 1', 'Associate Director - Delivery', 'Delivery', 'Clopay', 1, 'pdash@evoketechnologies.com', '12345' ),
( '523', 'Nageswara rao', 'Korlapati', '05-Jun-13', 'B3', 'Technical Lead', 'Microsoft Practice', 'Axalta', 1009, 'nkorlapati@evoketechnologies.com', '12345' ),
( '526', 'Sri Krishna', 'Kandulapati', '19-Jun-13', 'B1', 'Technical Associate', 'Oracle Practice', 'USP', 706, 'skandulapati@evoketechnologies.com', '12345' ),
( '529', 'Krishna Chaitanya', 'Raya', '25-Jun-13', 'A3', 'Data Entry Associate', 'BPO', 'CSC', 84, 'kraya@evoketechnologies.com', '12345' ),
( '532', 'Manikanta Kumar', 'Baggu', '22-Jul-13', 'B2', 'Senior Software Test Engineer', 'QA Practice', 'CSC', 34, 'mbaggu@evoketechnologies.com', '12345' ), 
( '534', 'Natesh Kumar', 'Chetty', '22-Jul-13', 'B3', 'Test Lead', 'QA Practice', 'CSC', 1039, 'nchetty@evoketechnologies.com', '12345' ),
( '546', 'Ravi Babu', 'Meda', '26-Sep-13', 'B3', 'Senior Analyst - SW', 'Microsoft Practice', 'Dominion', 1046, 'rmeda@evoketechnologies.com', '12345' ),
( '549', 'Venkata Raju', 'Pospati', '15-Oct-13', 'B3', 'Technical Lead', 'Java Practice', 'CSC', 787, 'vpospati@evoketechnologies.com', '12345' ),
( '554', 'Venkata Subbaiah', 'Pasupuleti', '21-Oct-13', 'B1', 'Software Engineer', 'BPM Practice', 'Axalta', 811, 'vpasupuleti@evoketechnologies.com', '12345' ),
( '557', 'Teja Jyothi', 'Nalamati', '04-Nov-13', 'B3', 'Technical Lead', 'Microsoft Practice', 'Clopay', 521, 'tnalamati@evoketechnologies.com', '12345' ),
( '561', 'Ganesh', 'joshi', '19-Nov-13', 'A2', 'Data Entry Associate', 'BPO', 'CSC', 84, 'gjoshi@evoketechnologies.com', '12345' ),
( '562', 'Aravind kumar', 'basava', '27-Nov-13', 'B1', 'Business Analyst', 'QA Practice', 'Axalta', 567, 'akbasava@evoketechnologies.com', '12345' ),
( '564', 'Younus', 'Suleman', '09-Dec-13', 'B2', 'Senior Content Writer', 'Support Staff', 'Evoke', 1046, 'ysuleman@evoketechnologies.com', '12345' ),
( '565', 'Naveen Reddy', 'Mettapally', '09-Dec-13', 'B3', 'Technical Lead', 'Java Practice', 'CSC', 2, 'nmettapally@evoketechnologies.com', '12345' ),
( '567', 'Chetana', 'Jampala', '16-Dec-13', 'C1', 'Project Manager', 'QA Practice', 'Axalta', 1, 'cjampala@evoketechnologies.com', '12345' ),
( '568', 'Lakshmi Narayana', 'Tallapragada', '19-Dec-13', 'B1', 'Network Engineer', 'IT & Infrastructure', 'IT & Infrastructure', 207, 'ltallapragada@evoketechnologies.com', '12345' ),
( '571', 'Basheer Mohammed', 'Ahmed Arif', '02-Jan-14', 'C1', 'Manager - Fraud Analysis', 'BPO', 'CSC', 787, 'bmohammed@evoketechnologies.com', '12345' ),
( '579', 'Harikanth', 'Sompalli', '16-Jan-14', 'B2', 'Senior Software Test Engineer', 'QA Practice', 'Dominion', 461, 'hsompalli@evoketechnologies.com', '12345' ),
( '580', 'Mohammed Khaleel', 'uddin', '17-Jan-14', 'B2', 'Senior Executive - Fraud Analyst', 'BPO', 'CSC', 571, 'kmohammed@evoketechnologies.com', '12345' ),
( '581', 'Mohammed Rahmath', 'Ali', '17-Jan-14', 'B2', 'Senior Executive - Fraud Analyst', 'BPO', 'CSC', 571, 'rmohammed@evoketechnologies.com', '12345' ),
( '584', 'Raju', 'Mandala', '20-Jan-14', 'B2', 'Senior Technical Associate', 'Java Practice', 'CSC', 648, 'rmandala@evoketechnologies.com', '12345' ),
( '585', 'Hanu Kiran', 'Nunabhatla', '21-Jan-14', 'B2', 'Senior Technical Associate', 'Java Practice', 'CSC', 679, 'hnunabhatla@evoketechnologies.com', '12345' ),
( '590', 'Parashuram', 'Thandra', '03-Feb-14', 'A2', 'Data Entry Associate', 'BPO', 'CSC', 84, 'pthandra@evoketechnologies.com', '12345' ),
( '592', 'Vasantha Kumar', 'Singamsetty', '03-Feb-14', 'B3', 'Technical Lead', 'Java Practice', 'CSC', 234, 'vsingamsetty@evoketechnologies.com', '12345' ),
( '594', 'Rajesh Kumar', 'Buddepu', '06-Feb-14', 'B3', 'Team Lead', 'Java Practice', 'CSC', 34, 'rbuddepu@evoketechnologies.com', '12345' ),
( '596', 'Hari Prasad', 'Palapotula', '17-Feb-14', 'B2', 'Senior Technical Associate', 'Java Practice', 'CSC', 648, 'hpalapotula@evoketechnologies.com', '12345' ),
( '598', 'Sujen', 'Maripally', '19-Feb-14', 'B2', 'Senior Technical Associate', 'Microsoft Practice', 'Clopay', 210, 'smaripally@evoketechnologies.com', '12345' ),
( '602', 'Sathish', 'Jannarapu', '11-Mar-14', 'B2', 'Senior Technical Associate', 'Java Practice', 'CSC', 108, 'sjannarapu@evoketechnologies.com', '12345' ),
( '605', 'Jhansi Rani', 'Nettem', '20-Mar-14', 'A2', 'Data Entry Associate', 'BPO', 'CSC', 84, 'Jnettem@evoketechnologies.com', '12345' ),
( '609', 'Lakshminarayan kumar', 'Gaddam', '02-Apr-14', 'B1', 'Executive - Fraud Analyst', 'BPO', 'CSC', 571, 'lgaddam@evoketechnologies.com', '12345' ),
( '620', 'Janardhana Reddy', 'Thummaluri', '16-May-14', 'B2', 'Senior Technical Associate', 'Java Practice', 'CSC', 151, 'jthummaluri@evoketechnologies.com', '12345' ),
( '627', 'Meher Santosh', 'Kuralla', '21-May-14', 'B2', 'Senior Software Test Engineer', 'QA Practice', 'CSC', 234, 'mkuralla@evoketechnologies.com', '12345' ),
( '630', 'Santhosh Kumar', 'Aella', '26-May-14', 'B1', 'Technical Associate', 'Oracle Practice', 'Oracle Practice', 896, 'saella@evoketechnologies.com', '12345' ),
( '633', 'Parameswara Reddy', 'Polu', '02-Jun-14', 'B2', 'Senior Software Test Engineer', 'QA Practice', 'Axalta', 809, 'ppolu@evoketechnologies.com', '12345' ),
( '635', 'VijayaLaksmi', 'Mutyala', '02-Jun-14', 'B2', 'Senior Technical Associate', 'Open Source Practice', 'Dominion', 897, 'vmutyala@evoketechnologies.com', '12345' ),
( '637', 'Rajesh', 'Yelichala', '13-Jun-14', 'B2', 'Senior Technical Associate', 'Java Practice', 'CSC', 658, 'ryelichala@evoketechnologies.com', '12345' ),
( '640', 'Srinivas', 'Gandrathi', '18-Jun-14', 'B3', 'Test Lead', 'QA Practice', 'CSC', 142, 'sgandrathi@evoketechnologies.com', '12345' ),
( '642', 'Vasumathi', 'Adwant', '20-Jun-14', 'C1', 'Associate Manager - HR', 'HR', 'HRBP', 1019, 'vadwant@evoketechnologies.com', '12345' ),
( '645', 'Kumaraswamy Joseph', 'Ashley Paul', '30-Jun-14', 'C1', 'Associate Manager - Fraud Analysis', 'BPO', 'CSC', 571, 'apaul@evoketechnologies.com', '12345' ),
( '646', 'Shashidhara Reddy', 'Karrevula', '07-Jul-14', 'B2', 'Senior Technical Associate', 'Microsoft Practice', 'CSC', 483, 'skarrevula@evoketechnologies.com', '12345' ), 
( '648', 'Pranavi Latha Thirumala Reddy', 'Basani', '07-Jul-14', 'C1', 'Project Manager', 'QA Practice', 'CSC', 787, 'pbasani@evoketechnologies.com', '12345' ),
( '651', 'Shiva Prasad', 'Banda', '09-Jul-14', 'B1', 'Software Test Engineer', 'QA Practice', 'CSC', 503, 'sbanda@evoketechnologies.com', '12345' ),
( '655', 'Sekhar', 'Bethalam', '16-Jul-14', 'B2', 'Senior Technical Associate', 'Mobility Practice', 'Dominion', 756, 'sbethalam@evoketechnologies.com', '12345' ),
( '658', 'Nithin', 'Khamitkar', '01-Aug-14', 'B3', 'Lead Business Analyst', 'QA Practice', 'CSC', 212, 'nkhamitkar@evoketechnologies.com', '12345' ),
( '660', 'Janaki Ramakrishna', 'Pothureddi', '05-Aug-14', 'B2', 'Senior Software Test Engineer', 'QA Practice', 'Clopay', 156, 'jpothureddi@evoketechnologies.com', '12345' ),
( '663', 'Sairam Babu', 'Gatti', '18-Aug-14', 'B2', 'Senior Software Test Engineer', 'BI Practice', 'CSC', 15, 'sgatti@evoketechnologies.com', '12345' ),
( '666', 'Sravanth', 'Addanki', '27-Aug-14', 'B2', 'Senior Technical Associate', 'Mobility Practice', 'Dominion', 756, 'saddanki@evoketechnologies.com', '12345' ),
( '669', 'Satish Kumar', 'Pasedla', '12-Sep-14', 'B1', 'Software Test Engineer', 'QA Practice', 'CSC', 151, 'spasedla@evoketechnologies.com', '12345' ), 
( '670', 'Surendra Babu', 'Botlagunta', '18-Sep-14', 'B2', 'Senior Technical Associate', 'Java Practice', 'CSC', 549, 'sbotlagunta@evoketechnologies.com', '12345' ),
( '675', 'Mallikarjun', 'Madireddy', '06-Oct-14', 'A2', 'Data Entry Associate', 'BPO', 'CSC', 84, 'mmadireddy@evoketechnologies.com', '12345' ),
( '679', 'Ravi Prasad', 'Valugubelli', '22-Oct-14', 'B3', 'Technical Lead', 'Java Practice', 'CSC', 15, 'rvalugubelli@evoketechnologies.com', '12345' ),
( '680', 'Sobha Rani', 'Allamsetti', '27-Oct-14', 'A2', 'Data Entry Associate', 'BPO', 'CSC', 84, 'sallamsetti@evoketechnologies.com', '12345' ),
( '681', 'Anitha', 'Nimmagadda', '27-Oct-14', 'A2', 'Data Entry Associate', 'BPO', 'CSC', 84, 'animmagadda@evoketechnologies.com', '12345' ),
( '682', 'Bhaskara Rao', 'Madala', '30-Oct-14', 'B3', 'Specialist - Finance', 'Finance', 'Accounts', 1, 'bmadala@evoketechnologies.com', '12345' ),
( '684', 'Shaik Mohammed', 'Shariff', '03-Nov-14', 'B3', 'Senior Analyst - SW', 'Open Source Practice', 'Dominion', 1046, 'sshariff@evoketechnologies.com', '12345' ),
( '686', 'Sunitha', 'Madela', '07-Nov-14', 'B2', 'Senior Technical Associate', 'Oracle Practice', 'USP', 706, 'smadela@evoketechnologies.com', '12345' ),
( '688', 'Arun Kumar', 'Baswapuram', '17-Nov-14', 'B1', 'Technical Associate', 'Microsoft Practice', 'Axalta', 279, 'abaswapuram@evoketechnologies.com', '12345' ),
( '689', 'Rajnikant Sayyaram', 'Hamand', '18-Nov-14', 'B2', 'Senior Technical Associate', 'Java Practice', 'Clopay', 12, 'rhamand@evoketechnologies.com', '12345' ),
( '692', 'Rajender Reddy', 'Kankanala', '26-Nov-14', 'B1', 'Technical Recruiter - US', 'Support Staff', 'Evoke', 866, 'rkankanala@evoketechnologies.com', '12345' ),
( '696', 'Prudhvi Varma', 'Kanumuri', '22-Dec-14', 'A2', 'Data Entry Associate', 'BPO', 'CSC', 84, 'pkanumuri@evoketechnologies.com', '12345' ),
( '698', 'Pradeep Kumar', 'Gadi', '31-Dec-14', 'B3', 'Technical Lead', 'Java Practice', 'CSC', 142, 'pgadi@evoketechnologies.com', '12345' ),
( '700', 'Venkata Subbarao', 'Nambolu', '31-Dec-14', 'A2', 'Data Entry Associate', 'BPO', 'CSC', 84, 'vnambolu@evoketechnologies.com', '12345' ),
( '701', 'Bhanu Prasad', 'Yadlapalli', '05-Jan-15', 'B2', 'Senior Business Analyst', 'Oracle Practice', 'USP', 708, 'byadlapalli@evoketechnologies.com', '12345' ),
( '703', 'Raghavendra Reddy', 'Levidi', '05-Jan-15', 'B2', 'Senior Business Analyst', 'Oracle Practice', 'USP', 708, 'rlevidi@evoketechnologies.com', '12345' ),
( '704', 'Sridhar', 'Bandari', '05-Jan-15', 'B2', 'Senior Business Analyst', 'Oracle Practice', 'USP', 708, 'sbandari@evoketechnologies.com', '12345' ),
( '705', 'Venkata Anantha Padmanabha Rao', 'Annamraju', '05-Jan-15', 'C1', 'Project Manager', 'Oracle Practice', 'USP', 708, 'vannamraju@evoketechnologies.com', '12345' ),
( '706', 'Venkateswara Rao', 'Puligadda', '05-Jan-15', 'C1', 'Project Manager', 'Oracle Practice', 'Care', 738, 'vpuligadda@evoketechnologies.com', '12345' ),
( '707', 'Satish Chandra', 'Chennu', '05-Jan-15', 'B2', 'Senior Software Engineer', 'Oracle Practice', 'Keste', 706, 'schennu@evoketechnologies.com', '12345' ),
( '708', 'Venkata Kumar', 'Shanker Kundeti', '05-Jan-15', 'C3', 'Senior Architect', 'Oracle Practice', 'CSC', 0, 'skundeti@evoketechnologies.com', '12345' ),
( '711', 'Raju', 'Mala', '12-Jan-15', 'A2', 'Data Entry Associate', 'BPO', 'CSC', 84, 'rmala@evoketechnologies.com', '12345' ),
( '712', 'Satya Pavan Kumar', 'Alamuru', '12-Jan-15', 'B2', 'Senior Technical Associate', 'Java Practice', 'CSC', 658, 'salamuru@evoketechnologies.com', '12345' ),
( '713', 'Prabhakar Rao', 'Yalavarthi', '19-Jan-15', 'B3', 'Technical Lead', 'Oracle Practice', 'CSC', 446, 'pyalavarthi@evoketechnologies.com', '12345' ),
( '714', 'Rakesh', 'Merugu', '22-Jan-15', 'A2', 'Data Entry Associate', 'BPO', 'CSC', 84, 'rmerugu@evoketechnologies.com', '12345' ),
( '715', 'Koti Reddy', 'Gurram', '27-Jan-15', 'B2', 'Senior Technical Associate', 'QA Practice', 'Clopay', 156, 'kgurram@evoketechnologies.com', '12345' ),
( '718', 'Anooj Kumar', 'Vishwakarma', '09-Feb-15', 'C2', 'Business Development Manager', 'Sales', 'Inside Sales', 880, 'akumar@evoketechnologies.com', '12345' ),
( '719', 'Deva Prasad', 'Gajawada', '09-Feb-15', 'B3', 'Senior Analyst - Testing', 'QA Practice', 'CSC', 108, 'dgajawada@evoketechnologies.com', '12345' ),
( '722', 'Mahendar', 'Katuku', '11-Feb-15', 'A2', 'Data Entry Associate', 'BPO', 'CSC', 84, 'mkatuku@evoketechnologies.com', '12345' ),
( '724', 'Ganga Madhulika', 'Bonala', '23-Feb-15', 'A2', 'Data Entry Associate', 'BPO', 'CSC', 84, 'gbonala@evoketechnologies.com', '12345' ), 
( '727', 'Krushidar Reddy', 'Kandala', '16-Mar-15', 'B3', 'Specialist - Quality', 'QA Practice', 'Clopay', 156, 'kkandala@evoketechnologies.com', '12345' ),
( '728', 'Unus', 'Mahammad', '16-Mar-15', 'B2', 'Senior Software Test Engineer', 'QA Practice', 'QA Practice', 1088, 'umahammad@evoketechnologies.com', '12345' ), 
( '731', 'Venugopal Rao', 'Bathina', '23-Mar-15', 'B2', 'Senior Technical Associate', 'Java Practice', 'CSC', 134, 'vbathina@evoketechnologies.com', '12345' ),
( '732', 'Sandeep Kumar', 'Deshini', '24-Mar-15', 'B2', 'Senior Software Engineer', 'Java Practice', 'Clopay', 12, 'sdeshini@evoketechnologies.com', '12345' ),
( '733', 'Guntamukkala', 'Krishna', '26-Mar-15', 'B3', 'Technical Lead', 'Oracle Practice', 'Clopay', 12, 'kguntamukkala@evoketechnologies.com', '12345' ),
( '734', 'Ankammarao', 'Ambati', '30-Mar-15', 'B1', 'Technical Associate', 'Java Practice', 'Axalta', 348, 'aambati@evoketechnologies.com', '12345' ),
( '736', 'Sasikanth  Reddy', 'Kanjula', '01-Apr-15', 'A2', 'Associate Business Analyst', 'Oracle Practice', 'Care', 708, 'skanjula@evoketechnologies.com', '12345' ),
( '737', 'Balaji Prasad', 'Boyina', '02-Apr-15', 'B2', 'Senior Technical Associate', 'Microsoft Practice', 'Axalta', 67, 'bboyina@evoketechnologies.com', '12345' ),
( '738', 'Subbarao', 'Tanikella', '06-Apr-15', 'C2', 'Delivery Manager', 'Delivery', 'Oracle Practice', 0, 'stanikella@evoketechnologies.com', '12345' ),
( '739', 'Venkata Rama Raju', 'Gunturi', '21-Apr-15', 'B2', 'Senior Software Test Engineer', 'QA Practice', 'Clopay', 156, 'vgunturi@evoketechnologies.com', '12345' ),
( '741', 'Viswanadha Pavan', 'Namburi', '27-Apr-15', 'B2', 'Senior Software Test Engineer', 'QA Practice', 'Clopay', 521, 'vnamburi@evoketechnologies.com', '12345' ),
( '743', 'Veera Sandeep', 'Yadiki', '01-May-15', 'B2', 'Senior Executive -HR', 'HR', 'Recruitment', 215, 'vyadiki@evoketechnologies.com', '12345' ),
( '744', 'Rama Naga', 'Satya Prasad Balla', '06-May-15', 'B2', 'Senior Technical Associate', 'Java Practice', 'CSC', 756, 'rballa@evoketechnologies.com', '12345' ),
( '756', 'Venkatesh', 'Anumalla', '01-Jun-15', 'B3', 'Team Lead', 'Java Practice', 'CSC', 34, 'vanumalla@evoketechnologies.com', '12345' ),
( '758', 'Kankana', 'Choudhury', '10-Jun-15', 'C2', 'Practice Lead - Mobility', 'Mobility Practice', 'Mobility Practice', 1, 'kchoudhury@evoketechnologies.com', '12345' ),
( '759', 'Uma Maheshwari', 'Shanka', '15-Jun-15', 'B1', 'Executive - Admin and Facilities', 'Support Staff', 'Evoke', 1058, 'ushanka@evoketechnologies.com', '12345' ),
( '762', 'Sairam', 'appannagari', '23-Jun-15', 'B2', 'Senior Software Engineer', 'Microsoft Practice', 'Axalta', 523, 'sappannagari@evoketechnologies.com', '12345' ),
( '763', 'Kishor', 'Kodam', '24-Jun-15', 'B2', 'Senior Technical Associate', 'Microsoft Practice', 'CSC', 787, 'kkodam@evoketechnologies.com', '12345' ),
( '765', 'Surya Bhagavan', 'Padala', '25-Jun-15', 'B1', 'Technical Associate', 'BPM Practice', 'Axalta', 348, 'spadala@evoketechnologies.com', '12345' ),
( '768', 'Sabarigireesh', 'Arakkal Mohandas', '01-Jul-15', 'C1', 'Associate Manager', 'Support Staff', 'Evoke', 880, 'smohandas@evoketechnologies.com', '12345' ),
( '769', 'Ramu', 'Vankayala', '03-Jul-15', 'B2', 'Senior Software Engineer', 'Oracle Practice', 'Clopay', 12, 'rvankayala@evoketechnologies.com', '12345' ),
( '770', 'Sreeharsha', 'Maddoju', '06-Jul-15', 'B3', 'Technical Lead', 'Microsoft Practice', 'Microsoft Practice', 1, 'smaddoju@evoketechnologies.com', '12345' ),
( '772', 'Ravindra', 'Adurty', '06-Jul-15', 'B1', 'System Administrator-Cloud', 'IT & Infrastructure', 'IT & Infrastructure', 207, 'radurty@evoketechnologies.com', '12345' ),
( '776', 'Dinesh Reddy', 'Thirumaredy', '13-Jul-15', 'B1', 'Technical Associate', 'Support Staff', 'Evoke', 564, 'dthirumareddy@evoketechnologies.com', '12345' ),
( '779', 'Yatin', 'Sharma', '16-Jul-15', 'B1', 'Technical Associate', 'Microsoft Practice', 'Axalta', 1009, 'ysharma@evoketechnologies.com', '12345' ),
( '780', 'Sundeep', 'Mohanraj', '20-Jul-15', 'C2', 'Business Development Manager', 'Sales', 'Inside Sales', 880, 'smohanraj@evoketechnologies.com', '12345' ),
( '781', 'Venkatesh', 'Bandarulanka', '22-Jul-15', 'A2', 'Data Entry Associate', 'BPO', 'CSC', 84, 'vbandarlanka@evoketechnologies.com', '12345' ),
( '784', 'Haribabu', 'Itikala', '28-Jul-15', 'B1', 'Technical Associate', 'Open Source Practice', 'Open Source Practice', 960, 'hitikala@evoketechnologies.com', '12345' ),
( '787', 'Aditya Pardhasaradhi', 'Bandaru', '03-Aug-15', 'C2', 'Delivery Manager', 'Delivery', 'CSC', 1039, 'abandaru@evoketechnologies.com', '12345' ),
( '789', 'Raju', 'Vangari', '10-Aug-15', 'B2', 'Senior Executive-Digital Marketing', 'Support Staff', 'Evoke', 564, 'rvangari@evoketechnologies.com', '12345' ),
( '790', 'Manoj', 'Morampudi', '10-Aug-15', 'A2', 'Data Entry Associate', 'BPO', 'CSC', 84, 'mmorampudi@evoketechnologies.com', '12345' ),
( '792', 'Ajay Prasad', 'Chityala', '10-Aug-15', 'B1', 'Executive - Fraud Analyst', 'BPO', 'CSC', 571, 'achityala@evoketechnologies.com', '12345' ),
( '795', 'Naveen Kumar', 'Ambati', '25-Aug-15', 'B1', 'Software Test Engineer', 'QA Practice', 'CSC', 142, 'nambati@evoketechnologies.com', '12345' ),
( '796', 'Rajendra Kumar', 'Panda', '01-Sep-15', 'B1', 'Security Analyst', 'Support Staff', 'Clopay', 156, 'rpanda@evoketechnologies.com', '12345' ),
( '797', 'Abhiram', 'Dharmavarapu', '01-Sep-15', 'B1', 'Technical Associate', 'Microsoft Practice', 'Axalta', 523, 'adharmavarapu@evoketechnologies.com', '12345' ),
( '801', 'Sankara Varaprasad', 'Krishnagiri Venkobarao', '14-Sep-15', 'B1', 'Technical Associate', 'Microsoft Practice', 'Clopay', 1040, 'skvenkobarao@evoketechnologies.com', '12345' ),
( '802', 'Ramakrishna', 'Somepalli', '16-Sep-15', 'B2', 'Senior Software Test Engineer', 'QA Practice', 'Clopay', 521, 'rsomepalli@evoketechnologies.com', '12345' ),
( '804', 'Rajesh Chand', 'Rayana', '16-Sep-15', 'B2', 'Senior Business Analyst', 'QA Practice', 'CSC', 549, 'rrayana@evoketechnologies.com', '12345' ),
( '805', 'Srujana', 'Kanaparthi', '18-Sep-15', 'B2', 'Senior Technical Associate', 'Sales Force Practice', 'CSC', 1039, 'skanaparthi@evoketechnologies.com', '12345' ),
( '806', 'Saleem', 'Shaik', '18-Sep-15', 'B2', 'Senior Technical Associate', 'Microsoft Practice', 'CSC', 212, 'sshaik@evoketechnologies.com', '12345' ),
( '809', 'Shiva Kumar', 'Nagam', '25-Sep-15', 'B3', 'Test Lead', 'QA Practice', 'Axalta', 1046, 'snagam@evoketechnologies.com', '12345' ),
( '810', 'Vijaya Venkata Bhaskar', 'Pedapudi', '28-Sep-15', 'B1', 'Technical Associate', 'Java Practice', 'CSC', 151, 'vpedapudi@evoketechnologies.com', '12345' ),
( '811', 'Sairam Kalyan', 'Kakarala', '28-Sep-15', 'B1', 'Technical Associate', 'BPM Practice', 'Axalta', 348, 'skakarala@evoketechnologies.com', '12345' ),
( '814', 'Karthikeya', 'Adavani', '30-Sep-15', 'B2', 'Senior Technical Associate', 'Microsoft Practice', 'CSC', 483, 'kadavani@evoketechnologies.com', '12345' ),
( '819', 'Satya Geeta', 'Krishna Siriki', '05-Oct-15', 'B2', 'Senior Exectutive - HR', 'HR', 'Recruitment', 109, 'ssiriki@evoketechnologies.com', '12345' ),
( '820', 'Nangunoori', 'Naveen Kumar', '07-Oct-15', 'B2', 'Senior Technical Associate', 'Java Practice', 'CSC', 549, 'nnangunoori@evoketechnologies.com', '12345' ),
( '827', 'Sunil Kumar', 'Chakravaram', '10-Nov-15', 'B2', 'Senior Technical Associate', 'Microsoft Practice', 'Dominion', 1046, 'schakravaram@evoketechnologies.com', '12345' ),
( '829', 'Vineeth Kumar', 'Vyasabhattu', '13-Nov-15', 'B1', 'Technical Associate', 'BPM Practice', 'BPM Practice', 348, 'vvyasabhattu@evoketechnologies.com', '12345' ),
( '833', 'Srinivas Rao', 'Challagolla', '19-Nov-15', 'B3', 'Technical Lead', 'Microsoft Practice', 'Dominion', 1046, 'schallagolla@evoketechnologies.com', '12345' ),
( '834', 'Bindu', 'Bokka', '23-Nov-15', 'B1', 'Technical Associate', 'Microsoft Practice', 'Microsoft Practice', 1, 'bbokka@evoketechnologies.com', '12345' ),
( '840', 'Palem', 'Bhanu Prakash', '01-Dec-15', 'B2', 'Senior Technical Associate', 'Microsoft Practice', 'Microsoft Practice', 1, 'bpalem@evoketechnologies.com', '12345' ),
( '842', 'Debasmita', 'Pradhan', '01-Dec-15', 'B1', 'Business Analyst', 'QA Practice', 'Clopay', 210, 'dpradhan@evoketechnologies.com', '12345' ),
( '843', 'Priya Sudha', 'Srinivasan', '03-Dec-15', 'A2', 'Data Entry Associate', 'BPO', 'CSC', 84, 'psrinivasan@evoketechnologies.com', '12345' ),
( '850', 'Thummalapalli Raja', 'Naresh', '16-Dec-15', 'A2', 'Data Entry Associate', 'BPO', 'CSC', 84, 'rtummalapalli@evoketechnologies.com', '12345' ),
( '851', 'Anusha Devi', 'Gurram', '17-Dec-15', 'B2', 'Senior Technical Associate', 'Microsoft Practice', 'Axalta', 567, 'agurram@evoketechnologies.com', '12345' ),
( '853', 'Bhumesh', 'Mushnam', '24-Dec-15', 'B2', 'Senior Technical Associate', 'BI Practice', 'CSC', 663, 'bmushnam@evoketechnologies.com', '12345' ),
( '854', 'Aneel Shanmukhi', 'Amaravadi', '28-Dec-15', 'B2', 'Senior Technical Associate', 'BI Practice', 'CSC', 29, 'aamaravadi@evoketechnologies.com', '12345' ),
( '855', 'Immadi', 'Venu Gopal Reddy', '28-Dec-15', 'B2', 'Senior Technical Associate', 'Java Practice', 'Axalta', 960, 'vimmadi@evoketechnologies.com', '12345' ),
( '856', 'Praveen Alwar', 'Pagadala', '04-Jan-16', 'C3', 'Senior Architect', 'Microsoft Practice', 'Clopay', 521, 'ppagadala@evoketechnologies.com', '12345' ),
( '858', 'Shiny Reddy', 'Salivindala', '12-Jan-16', 'B1', 'Software Test Engineer', 'QA Practice', 'CSC', 648, 'ssalivindala@evoketechnologies.com', '12345' ),
( '859', 'Mantha Venkata', 'Satya Sai Kiran', '18-Jan-16', 'B1', 'Technical Associate', 'Java Practice', 'Axalta', 960, 'vmantha@evoketechnologies.com', '12345' ),
( '861', 'Santosh Kumar', 'Madduri', '22-Jan-16', 'B1', 'Technical Associate', 'Oracle Practice', 'Clopay', 738, 'smadduri@evoketechnologies.com', '12345' ),
( '862', 'Sowmya', 'Kanuri', '28-Jan-16', 'B2', 'Senior Technical Associate', 'Microsoft Practice', 'Microsoft Practice', 1, 'skanuri@evoketechnologies.com', '12345' ),
( '865', 'Madhurai', 'Madhu Babu', '01-Feb-16', 'B2', 'Senior Technical Associate', 'Open Source Practice', 'Clopay', 960, 'mmadhurai@evoketechnologies.com', '12345' ),
( '866', 'Srikanth Reddy', 'Allu', '04-Feb-16', 'B3', 'Lead - QMS', 'Support Staff', 'Evoke', 521, 'sallu@evoketechnologies.com', '12345' ),
( '868', 'Chandra Shekhar', 'Goka', '12-Feb-16', 'B2', 'Senior Technical Associate', 'Java Practice', 'CSC', 648, 'cgoka@evoketechnologies.com', '12345' ),
( '869', 'Harish Kumar', 'Daga', '12-Feb-16', 'C1', 'Project Manager', 'Microsoft Practice', 'Dominion', 1046, 'hdaga@evoketechnologies.com', '12345' ),
( '870', 'P', 'Sumana', '15-Feb-16', 'B3', 'Specialist - Software Developer', 'Java Practice', 'CSC', 483, 'spandey@evoketechnologies.com', '12345' ),
( '871', 'Aakash Rewaram', 'Bhoyar', '15-Feb-16', 'B1', 'Technical Associate', 'Microsoft Practice', 'Clopay', 557, 'abhoyar@evoketechnologies.com', '12345' ),
( '874', 'Ravi Chandra', 'Srirama Kavacham', '17-Feb-16', 'B2', 'Senior Technical Associate', 'Java Practice', 'CSC', 895, 'rsriramakavacham@evoketechnologies.com', '12345' ),
( '875', 'Sai Kiran', 'Shere', '18-Feb-16', 'B2', 'Senior Technical Associate', 'Oracle Practice', 'Clopay', 12, 'sshere@evoketechnologies.com', '12345' ),
( '877', 'Padmaja', 'Indukuri', '18-Feb-16', 'A2', 'Data Entry Associate', 'BPO', 'CSC', 84, 'pindukuri@evoketechnologies.com', '12345' ),
( '878', 'Rajendar', 'Lomte', '22-Feb-16', 'B3', 'Test Lead', 'QA Practice', 'Clopay', 521, 'rlomte@evoketechnologies.com', '12345' ),
( '880', 'Venkata Appala Naidu', 'Chodavarapu', '29-Feb-16', 'D2', 'Senior Practice Director', 'Sales', 'Sales', 1, 'vnaidu@evoketechnologies.com', '12345' ),
( '884', 'Pandiri', 'Ashok Vishal', '03-Mar-16', 'B1', 'Technical Associate', 'Java Practice', 'CSC', 594, 'apandiri@evoketechnologies.com', '12345' ),
( '885', 'Sudhakar', 'Bethamsetty', '04-Mar-16', 'B3', 'Technical Lead', 'BI Practice', 'CSC', 663, 'sbethamsetty@evoketechnologies.com', '12345' ),
( '886', 'Syed', 'Khaled', '07-Mar-16', 'B1', 'Executive - Fraud Analyst', 'BPO', 'CSC', 571, 'ksyed@evoketechnologies.com', '12345' ),
( '887', 'Navya', 'Kotra', '09-Mar-16', 'B2', 'Senior Software Test Engineer', 'QA Practice', 'CSC', 2, 'nkotra@evoketechnologies.com', '12345' ),
( '888', 'Haseena', 'Fathima', '14-Mar-16', 'B3', 'Team Lead', 'Java Practice', 'Axalta', 880, 'hfathima@evoketechnologies.com', '12345' ),
( '890', 'Shaik Mahammad', 'Hussain', '14-Mar-16', 'B1', 'Technical Associate', 'Java Practice', 'Prime Tech', 348, 'shussain@evoketechnologies.com', '12345' ),
( '891', 'Rajendra Dnyaneshwar', 'Mote', '14-Mar-16', 'B1', 'Technical Associate', 'Microsoft Practice', 'Clopay', 557, 'rmote@evoketechnologies.com', '12345' ),
( '893', 'Karthik', 'Varagini', '16-Mar-16', 'B2', 'Senior Technical Associate', 'Microsoft Practice', 'Axalta', 279, 'kvaragini@evoketechnologies.com', '12345' ),
( '895', 'LakshmiKanth', 'Kovilapalli', '21-Mar-16', 'B3', 'Technical Lead', 'Java Practice', 'CSC', 212, 'lkovilapalli@evoketechnologies.com', '12345' ),
( '896', 'Kasi Viswanadha Raju', 'Penmetsa', '21-Mar-16', 'B3', 'Technical Lead', 'Oracle Practice', 'Oracle Practice', 0, 'kpenmetsa@evoketechnologies.com', '12345' ),
( '897', 'Somasila Bhavani', 'Praneeth', '28-Mar-16', 'B3', 'Technical Lead', 'Open Source Practice', 'Dominion', 1046, 'psomasila@evoketechnologies.com', '12345' ),
( '900', 'Archana', 'Sahu', '01-Apr-16', 'B1', 'Executive-HR', 'HR', 'Recruitment', 215, 'asahu@evoketechnologies.com', '12345' ),
( '901', 'Gaurav', 'Rana', '01-Apr-16', 'B1', 'Technical Associate', 'Java Practice', 'CSC', 594, 'grana@evoketechnologies.com', '12345' ),
( '902', 'Anand Ravindra Babu', 'Tirupathi', '01-Apr-16', 'A3', 'Junior Administrator-Cloud', 'IT & Infrastructure', 'IT & Infrastructure', 222, 'atirupathi@evoketechnologies.com', '12345' ),
( '904', 'Venkatrao', 'Gangineni', '04-Apr-16', 'B2', 'Senior Technical Associate', 'BI Practice', 'CSC', 663, 'vgangineni@evoketechnologies.com', '12345' ),
( '905', 'Kalyana Chakravarthi', 'Adavi', '04-Apr-16', 'B2', 'Senior Software Test Engineer', 'QA Practice', 'Clopay', 156, 'kadavi@evoketechnologies.com', '12345' ),
( '907', 'Chaitanya Kumar', 'Adhikamsetty', '06-Apr-16', 'B1', 'Technical Associate', 'Microsoft Practice', 'Axalta', 1009, 'cadhikamsetty@evoketechnologies.com', '12345' ),
( '909', 'Ratna Kumari', 'Kolli', '13-Apr-16', 'B1', 'Technical Associate', 'Java Practice', 'Java Practice', 420, 'rkolli@evoketechnologies.com', '12345' ),
( '910', 'Vikas Chandra', 'Mehta', '14-Apr-16', 'B2', 'Senior Technical Associate', 'Microsoft Practice', 'CSC', 483, 'vmehta@evoketechnologies.com', '12345' ),
( '912', 'Bhanu Prakash', 'Thunuguntla', '18-Apr-16', 'C1', 'Associate Architect - Technical', 'Microsoft Practice', 'Axalta', 1046, 'bthunuguntla@evoketechnologies.com', '12345' ),
( '913', 'Kota Anji', 'Reddy', '18-Apr-16', 'B1', 'Technical Associate', 'Microsoft Practice', 'CSC', 483, 'akota@evoketechnologies.com', '12345' ),
( '914', 'Abhishekha Reddy', 'Dupana', '27-Apr-16', 'B2', 'Senior Technical Associate', 'Open Source Practice', 'Dominion', 1046, 'adupana@evoketechnologies.com', '12345' ),
( '917', 'Sampara', 'Bala Deepika', '02-May-16', 'B1', 'Executive-HR', 'HR', 'HRBP', 1019, 'bsampara@evoketechnologies.com', '12345' ),
( '919', 'Md', 'Badiyuzama', '03-May-16', 'B3', 'Technical Lead', 'Java Practice', 'CSC', 1039, 'bmohammad@evoketechnologies.com', '12345' ),
( '921', 'Rajkumar', 'Pasunuri', '05-May-16', 'B2', 'Senior Technical Associate', 'Java Practice', 'CSC', 594, 'rpasunuri@evoketechnologies.com', '12345' ),
( '922', 'Zakeeruddin', 'Mohammed', '06-May-16', 'B1', 'Technical Associate', 'Sales Force Practice', 'CSC', 974, 'zmohd@evoketechnologies.com', '12345' ),
( '923', 'Srinivas', 'Pabballa', '06-May-16', 'B1', 'Technical Associate', 'Microsoft Practice', 'Axalta', 1009, 'spabballa@evoketechnologies.com', '12345' ),
( '928', 'Dasari Shanmuk', 'Venkata Krishna Durga Rao', '16-May-16', 'B1', 'Technical Associate', 'Microsoft Practice', 'CSC', 483, 'sdasari1@evoketechnologies.com', '12345' ),
( '930', 'kandukuri', 'VVSNBLN Murthy', '16-May-16', 'B2', 'Senior Technical Associate', 'QA Practice', 'CSC', 483, 'vkandukuri@evoketechnologies.com', '12345' ),
( '932', 'Bandaru', 'Venkata Siva Prasad', '19-May-16', 'B2', 'Senior Software Test Engineer', 'QA Practice', 'Clopay', 878, 'vbandaru@evoketechnologies.com', '12345' ),
( '933', 'Annamma', 'Lanka', '23-May-16', 'B1', 'Technical Associate', 'Microsoft Practice', 'Dominion', 546, 'alanka@evoketechnologies.com', '12345' ),
( '937', 'Sri Chakra Teja', 'Tadikonda', '26-May-16', 'B1', 'Software Test Engineer', 'QA Practice', 'CSC', 483, 'stadikonda@evoketechnologies.com', '12345' ),
( '939', 'Sravani', 'Davuluri', '31-May-16', 'B1', 'Software Test Engineer', 'QA Practice', 'Axalta', 811, 'sdavuluri@evoketechnologies.com', '12345' ),
( '940', 'Monica', 'Mandal', '01-Jun-16', 'B3', 'Technical Lead', 'Open Source Practice', 'Open Source Practice', 880, 'mmandal@evoketechnologies.com', '12345' ),
( '941', 'Balaji', 'Goddu', '01-Jun-16', 'B1', 'Technical Associate', 'BPM Practice', 'BPM Practice', 348, 'bgoddu@evoketechnologies.com', '12345' ),
( '943', 'Muralikrishna', 'Tottimpudi', '13-Jun-16', 'B2', 'Senior Technical Associate', 'Open Source Practice', 'Open Source Practice', 960, 'mtottimpudi@evoketechnologies.com', '12345' ),
( '944', 'Ashok Sattaiah', 'Kota', '13-Jun-16', 'B1', 'Technical Associate', 'Microsoft Practice', 'Axalta', 523, 'akota1@evoketechnologies.com', '12345' ),
( '945', 'Prashanth', 'Nama', '13-Jun-16', 'B2', 'Senior Software Test Engineer', 'QA Practice', 'Clopay', 521, 'pnama@evoketechnologies.com', '12345' ),
( '947', 'Narendra', 'Talasila', '15-Jun-16', 'A2', 'Data Entry Associate', 'BPO', 'CSC', 84, 'ntalasila@evoketechnologies.com', '12345' ),
( '948', 'Uma Devi', 'Narasimhulu', '16-Jun-16', 'B2', 'Senior Software Test Engineer', 'QA Practice', 'CSC', 483, 'unarasimhulu@evoketechnologies.com', '12345' ),
( '950', 'Vijaya Krishna', 'Yenneti', '17-Jun-16', 'B1', 'Software Test Engineer', 'QA Practice', 'CSC', 134, 'vyenneti@evoketechnologies.com', '12345' ),
( '951', 'Kishore', 'Sabbineni', '20-Jun-16', 'B1', 'Technical Associate', 'Java Practice', 'CSC', 648, 'ksabbineni@evoketechnologies.com', '12345' ),
( '953', 'Radha', 'Rani T', '20-Jun-16', 'B2', 'Senior Software Test Engineer', 'QA Practice', 'CSC', 42, 'rturumalla@evoketechnologies.com', '12345' ),
( '954', 'Veera Raghava Reddy', 'Baikati', '27-Jun-16', 'B3', 'Lead-Data Science', 'R&D Practice', 'R&D', 1039, 'vbaikati@evoketechnologies.com', '12345' ),
( '955', 'Rajam', 'Vigneshwar', '28-Jun-16', 'B1', 'Technical Associate', 'Open Source Practice', 'Dominion', 420, 'vrajam@evoketechnologies.com', '12345' ),
( '958', 'Suneetha', 'Rachepalli', '04-Jul-16', 'B2', 'Senior Technical Associate', 'Oracle Practice', 'Oracle Practice', 446, 'srachepalli@evoketechnologies.com', '12345' ),
( '959', 'Venkateswara Rao', 'Buchiraju', '06-Jul-16', 'B2', 'Senior Technical Associate', 'Open Source Practice', 'Ritas', 1046, 'vbuchiraju@evoketechnologies.com', '12345' ),
( '960', 'Praveen Kumar', 'Thirupathi', '06-Jul-16', 'B3', 'Technical Lead', 'Open Source Practice', 'Open Source Practice', 880, 'pthirupathi@evoketechnologies.com', '12345' ),
( '963', 'Mahendra Reddy', 'Oruganti', '12-Jul-16', 'B2', 'Senior Technical Associate', 'BI Practice', 'CSC', 663, 'moruganti@evoketechnologies.com', '12345' ),
( '965', 'Raghu', 'Gaddamanugu', '18-Jul-16', 'B2', 'Senior Technical Associate', 'Microsoft Practice', 'CSC', 483, 'rgaddamanugu@evoketechnologies.com', '12345' ),
( '967', 'Chinmaya', 'Dash', '18-Jul-16', 'B1', 'Technical Associate', 'Microsoft Practice', 'Clopay', 175, 'cdash@evoketechnologies.com', '12345' ),
( '968', 'Naga Venkat Kumar', 'Sivarathri', '20-Jul-16', 'B2', 'Senior Software Test Engineer', 'QA Practice', 'Clopay', 521, 'nsivarathri@evoketechnologies.com', '12345' ),
( '969', 'Anurag', 'Boddapati', '20-Jul-16', 'B2', 'Senior Business Analyst', 'QA Practice', 'Axalta', 567, 'aboddapati@evoketechnologies.com', '12345' ),
( '970', 'Siddharth', 'Kalia', '21-Jul-16', 'B2', 'Senior Technical Associate', 'BI Practice', 'CSC', 134, 'skalia@evoketechnologies.com', '12345' ), 
( '971', 'Harish', 'Chandupatla', '22-Jul-16', 'B2', 'Senior Business Development Executive', 'Sales', 'Inside Sales', 348, 'hchandupatla@evoketechnologies.com', '12345' ),
( '974', 'Sambarajyam', 'Venu Adepu', '25-Jul-16', 'C1, L2', 'Senior Project Manager', 'Sales Force Practice', 'CSC', 1039, 'sadepu@evoketechnologies.com', '12345' ),
( '975', 'Mani Prakash', 'Sarana', '01-Aug-16', 'B1', 'Executive-HR', 'HR', 'Recruitment', 215, 'msarana@evoketechnologies.com', '12345' ), 
( '978', 'Jagadeesh', 'Penta', '04-Aug-16', 'B2', 'Senior Technical Associate', 'Open Source Practice', 'Open Source Practice', 960, 'jpenta@evoketechnologies.com', '12345' ),
( '979', 'Rajesh', 'Uriti', '08-Aug-16', 'B1', 'Technical Associate', 'BI Practice', 'CSC', 29, 'ruriti@evoketechnologies.com', '12345' ),
( '980', 'Sunil Kumar', 'Anjuru', '08-Aug-16', 'B1', 'Technical Associate', 'BI Practice', 'CSC', 663, 'sanjuru@evoketechnologies.com', '12345' ),
( '982', 'Karthik', 'Donagala', '08-Aug-16', 'B2', 'Senior Technical Associate', 'BPM Practice', 'BMS', 348, 'kdonagala@evoketechnologies.com', '12345' ),
( '983', 'Raghu Prakash', 'Bhongir', '10-Aug-16', 'C2', 'Business Development Manager', 'Sales', 'Inside Sales', 880, 'rbhongir@evoketechnologies.com', '12345' ),
( '984', 'Kishore', 'Borru', '10-Aug-16', 'B1', 'Technical Associate', 'Open Source Practice', 'Axalta', 1009, 'kborru@evoketechnologies.com', '12345' ),
( '986', 'Siva Sankar Raju', 'Keerthipati', '18-Aug-16', 'B3', 'Test Lead', 'QA Practice', 'CSC', 648, 'skeerthipati@evoketechnologies.com', '12345' ),
( '987', 'Krishna Chaitanya Kumar', 'Bolle', '19-Aug-16', 'B3', 'Lead Business Development', 'Sales', 'Inside Sales', 880, 'kbolle@evoketechnologies.com', '12345' ),
( '988', 'Naveen Kumar', 'Potharlanka', '29-Aug-16', 'C2', 'Business Development Manager', 'Sales', 'Inside Sales', 880, 'npotharlanka@evoketechnologies.com', '12345' ),
( '989', 'Meerja jafar Ali', 'Beg', '31-Aug-16', 'B1', 'Technical Associate', 'BI Practice', 'CSC', 663, 'jmeerja@evoketechnologies.com', '12345' ),
( '991', 'Raghavendra', 'Penjuri', '01-Sep-16', 'B2', 'Senior System Administrator', 'IT & Infrastructure', 'IT & Infrastructure', 207, 'rpenjuri@evoketechnologies.com', '12345' ),
( '992', 'Sandeep Kumar', 'Padam', '01-Sep-16', 'B2', 'Senior Software Test Engineer', 'QA Practice', 'CSC', 895, 'spadam@evoketechnologies.com', '12345' ),
( '997', 'Ramya Sree', 'Allada', '08-Sep-16', 'B2', 'Senior Technical Associate', 'Open Source Practice', 'Dominion', 897, 'rallada@evoketechnologies.com', '12345' ),
( '998', 'Ravikiran', 'Auti', '12-Sep-16', 'B1', 'Executive - Fraud Analyst', 'BPO', 'CSC', 571, 'rauti@evoketechnologies.com', '12345' ),
( '1002', 'Gowri Shanker', 'Raghuraman', '21-Sep-16', 'C2', 'Technical Architect', 'Microsoft Practice', 'Axalta', 880, 'graghuraman@evoketechnologies.com', '12345' ),
( '1003', 'V', 'Saritha', '22-Sep-16', 'C1', 'Project Manager', 'Support Staff', 'Evoke', 521, 'svemulapalli@evoketechnologies.com', '12345' ),
( '1004', 'Thota', 'Venu Kumar', '22-Sep-16', 'B3', 'Technical Lead', 'Oracle Practice', 'CSC', 708, 'vthota@evoketechnologies.com', '12345' ),
( '1005', 'Ravi Chandra', 'Kandavalli', '22-Sep-16', 'B1', 'Executive - Fraud Analyst', 'BPO', 'CSC', 571, 'rkandavalli@evoketechnologies.com', '12345' ),
( '1007', 'Sridhar', 'Akula', '26-Sep-16', 'B2', 'Senior Technical Associate', 'Microsoft Practice', 'Dominion', 546, 'sakula1@evoketechnologies.com', '12345' ),
( '1008', 'Maddipatla Kalyan', 'Chakravarthy', '28-Sep-16', 'B2', 'Senior Software Test Engineer', 'QA Practice', 'Clopay', 521, 'kmaddipatla@evoketechnologies.com', '12345' ),
( '1009', 'Sai Siva Rama Krishna', 'Bellum', '03-Oct-16', 'C1', 'Senior Project Manager', 'Microsoft Practice', 'Axalta', 1046, 'sbellum@evoketechnologies.com', '12345' ),
( '1011', 'Sarvani', 'Atcha', '06-Oct-16', 'B2', 'Senior Technical Associate', 'Big Data Practice', 'Big Data Practice', 880, 'satcha@evoketechnologies.com', '12345' ),
( '1012', 'Shanti Swaroop', 'Reddy', '06-Oct-16', 'B2', 'Senior Software Test Engineer', 'QA Practice', 'CSC', 483, 'sshanti@evoketechnologies.com', '12345' ),
( '1013', 'Krishna Kishore Reddy', 'Gaddam', '07-Oct-16', 'A3', 'Trainee Systems Engineer', 'IT & Infrastructure', 'IT & Infrastructure', 207, 'kgaddam@evoketechnologies.com', '12345' ),
( '1015', 'Sridhar Reddy', 'Jagamoni', '12-Oct-16', 'B2', 'Senior Technical Associate', 'Open Source Practice', 'Clopay', 1040, 'sjagamoni@evoketechnologies.com', '12345' ),
( '1016', 'Raghu', 'Kunchakuri', '17-Oct-16', 'B2', 'Senior Technical Associate', 'BI Practice', 'Axalta', 1046, 'rkunchakuri@evoketechnologies.com', '12345' ),
( '1017', 'Madhu Kumar', 'Lingala', '17-Oct-16', 'B1', 'Executive - Fraud Analyst', 'BPO', 'CSC', 571, 'mlingala@evoketechnologies.com', '12345' ),
( '1018', 'Nagabhushanam', 'Kunarapu', '17-Oct-16', 'B3', 'Technical Lead', 'BI Practice', 'Axalta', 1046, 'nkunarapu@evoketechnologies.com', '12345' ),
( '1019', 'Ramesh', 'Mantana', '17-Oct-16', 'D1, Level 2', 'Director-HR', 'HR', 'HRBP', 1, 'rmantana@evoketechnologies.com', '12345' ),
( '1020', 'Suman', 'Mamidi', '18-Oct-16', 'B3', 'Technical Lead', 'Java Practice', 'CSC', 756, 'smamidi@evoketechnologies.com', '12345' ),
( '1021', 'Kondapaneni', 'Seetaramaiah        ', '19-Oct-16', 'B2', 'Senior Technical Associate', 'Java Practice', 'CSC', 679, 'skondapaneni@evoketechnologies.com', '12345' ),
( '1023', 'Surya Nagendra', 'Garikapati', '31-Oct-16', 'B1', 'Executive - Fraud Analyst', 'BPO', 'CSC', 571, 'sgarikapati@evoketechnologies.com', '12345' ),
( '1024', 'Srikanth', 'Nagallapatu', '31-Oct-16', 'B1', 'Technical Associate', 'Microsoft Practice', 'Clopay', 175, 'snagallapatu@evoketechnologies.com', '12345' ),
( '1025', 'Anoosha', 'Jogu', '01-Nov-16', 'B1', 'Technical Associate', 'Sales Force Practice', 'Sales Force Practice', 974, 'ajogu@evoketechnologies.com', '12345' ),
( '1026', 'Kanak', 'Kumar', '02-Nov-16', 'B2', 'Senior Technical Associate', 'Mobility Practice', 'Clopay', 1119, 'kkumar@evoketechnologies.com', '12345' ),
( '1027', 'Thirumala rao', 'Mandava', '02-Nov-16', 'B2', 'Senior Technical Associate', 'Oracle Practice', 'CSC', 708, 'tmandava@evoketechnologies.com', '12345' ),
( '1028', 'Srinivas', 'Chebrolu', '07-Nov-16', 'A3', 'Trainee Software Engineer', 'BI Practice', 'Axalta', 1046, 'schebrolu@evoketechnologies.com', '12345' ),
( '1029', ' Venkata Prasanthi', 'Vegendla', '07-Nov-16', 'B1', 'Software Test Engineer', 'QA Practice', 'Clopay', 156, 'pvegendla@evoketechnologies.com', '12345' ),
( '1030', 'Sunil Kumar', 'Biche', '07-Nov-16', 'B2', 'Senior Technical Associate', 'BI Practice', 'Axalta', 1046, 'sbiche@evoketechnologies.com', '12345' ),
( '1031', 'Aditi', 'Sharma', '07-Nov-16', 'A3', 'Trainee Technical Associate', 'Java Practice', 'CSC', 648, 'asharma@evoketechnologies.com', '12345' ),
( '1032', 'Srikanth', 'Manne', '10-Nov-16', 'B1', 'Technical Associate', 'Sales Force Practice', 'Sales Force Practice', 974, 'smanne@evoketechnologies.com', '12345' ),
( '1033', 'Dodagatta Ramalingareddy', 'Gari Sreenath Reddy', '14-Nov-16', 'B1', 'Executive - Fraud Analyst', 'BPO', 'CSC', 571, 'sdodagatta@evoketechnologies.com', '12345' ),
( '1034', 'Sudheer', 'Mokkapati', '14-Nov-16', 'A3', 'Trainee Software Test Engineer', 'QA Practice', 'Axalta', 1009, 'smokkapati@evoketechnologies.com', '12345' ),
( '1035', 'Manoj Kumar', 'Kotturi', '14-Nov-16', 'B2', 'Senior Software Test Engineer', 'QA Practice', 'Clopay', 246, 'mkotturi@evoketechnologies.com', '12345' ),
( '1036', 'Uma Maheswari', 'Janapareddy', '17-Nov-16', 'B1', 'Accounts Executive', 'Finance', 'Accounts', 185, 'ujanapareddy@evoketechnologies.com', '12345' ),
( '1037', 'Vandana', 'Pavan Kumar', '17-Nov-16', 'B1', 'Software Test Engineer', 'QA Practice', 'Dominion', 461, 'pvandana@evoketechnologies.com', '12345' ),
( '1038', 'Mohammed', 'Sajeed', '21-Nov-16', 'B1', 'Executive - Fraud Analyst', 'BPO', 'CSC', 571, 'msajeed@evoketechnologies.com', '12345' ),
( '1039', 'Sukumar', 'Kasamsetty', '24-Nov-16', 'D1, Level 2', 'Director - Delivery', 'Delivery', 'CSC', 1, 'skasamsetty@evoketechnologies.com', '12345' ),
( '1040', 'Anil Kumar', 'Mukka', '24-Nov-16', 'B3', 'Technical Lead', 'Microsoft Practice', 'Clopay', 521, 'amukka@evoketechnologies.com', '12345' ),
( '1042', 'Venkatesh', 'Pasunuri', '28-Nov-16', 'B2', 'Senior Technical Associate', 'BI Practice', 'CSC', 663, 'vpasunuri@evoketechnologies.com', '12345' ),
( '1044', 'Srikanth', 'Karankoth', '28-Nov-16', 'B2', 'Senior Technical Associate', 'Java Practice', 'CSC', 1039, 'skarankoth@evoketechnologies.com', '12345' ),
( '1045', 'Ashok', 'Satharla', '01-Dec-16', 'B1', 'Technical Associate', 'Open Source Practice', 'Ritas', 420, 'asatharla@evoketechnologies.com', '12345' ),
( '1046', 'Rajesh', 'Kotnur', '19-Dec-16', 'D1, Level 1', 'Associate Director -Delivery', 'Delivery', 'Dominion', 1, 'rkotnur@evoketechnologies.com', '12345' ),
( '1047', 'Sainath', 'Vygala', '19-Dec-16', 'B1', 'Technical Associate', 'Sales Force Practice', 'Sales Force Practice', 974, 'svygala@evoketechnologies.com', '12345' ),
( '1048', 'Ravipati', 'Venkata Raghavendra', '19-Dec-16', 'B1', 'Technical Associate', 'Sales Force Practice', 'Sales Force Practice', 974, 'vravipati@evoketechnologies.com', '12345' ),
( '1049', 'Agilan', 'Deenadayalan', '21-Dec-16', 'B1', 'Technical Associate', 'Open Source Practice', 'Open Source Practice', 960, 'adeenadayalan@evoketechnologies.com', '12345' ),
( '1050', 'Venkata Satish Kumar', 'Nerella', '26-Dec-16', 'B2', 'Senior Technical Associate', 'Open Source Practice', 'Dominion', 1046, 'sneralla@evoketechnologies.com', '12345' ),
( '1051', 'Jyothi', 'Kolampu', '26-Dec-16', 'A2', 'Data Entry Associate', 'BPO', 'CSC', 84, 'jkolampu@evoketechnologies.com', '12345' ),
( '1052', 'Kurella Bhanu', 'Shankar', '02-Jan-17', 'B2', 'Senior Software Test Engineer', 'QA Practice', 'CSC', 483, 'bkurella@evoketechnologies.com', '12345' ),
( '1053', 'Asha', 'Basava', '02-Jan-17', 'A2', 'Data Entry Associate', 'BPO', 'CSC', 84, 'abasava@evoketechnologies.com', '12345' ),
( '1054', 'Parthik', 'Parekh', '02-Jan-17', 'B3', 'Test Lead', 'QA Practice', 'CSC', 142, 'pparekh@evoketechnologies.com', '12345' ),
( '1055', 'Vamsi Krishna', 'Kodali', '02-Jan-17', 'B2', 'Senior Software Test Engineer', 'QA Practice', 'CSC', 549, 'vkodali@evoketechnologies.com', '12345' ),
( '1056', 'Dhananjaya Rao', 'Budireddi', '09-Jan-17', 'B3', 'Technical Lead', 'Oracle Practice', 'CSC', 446, 'dbudireddi@evoketechnologies.com', '12345' ),
( '1058', 'Praveen Kumar Reddy', 'Ganapathireddi', '23-Jan-17', 'B3', 'Lead - Admin & Facilities', 'Support Staff', 'Evoke', 1019, 'pganapathireddy@evoketechnologies.com', '12345' ),
( '1059', 'Praveen Kumar', 'Maddi', '30-Jan-17', 'B1', 'Software Test Engineer', 'QA Practice', 'Clopay', 156, 'pmaddi@evoketechnologies.com', '12345' ),
( '1060', 'Shravika', 'Perikari', '30-Jan-17', 'B1', 'Executive-HR', 'HR', 'HRBP', 1019, 'sperikari@evoketechnologies.com', '12345' ),
( '1061', 'Sri Gowri Hariharan', 'Subramanyam', '30-Jan-17', 'B3', 'Lead -HR', 'HR', 'HRBP', 1019, 'sgowri@evoketechnologies.com', '12345' ),
( '1062', 'Aruna', 'Gangineni', '06-Feb-17', 'A3', 'Trainee Technical Associate', 'BI Practice', 'CSC', 29, 'agangineni@evoketechnologies.com', '12345' ),
( '1063', 'Anil Kumar', 'Mogamatam', '09-Feb-17', 'B3', 'Lead - Wintel', 'Support Staff', 'Clopay', 207, 'amogamatam@evoketechnologies.com', '12345' ),
( '1064', 'Frankline', 'Francis', '09-Feb-17', 'C2', 'Technical Architect', 'Java Practice', 'Java Practice', 880, 'ffrancis@evoketechnologies.com', '12345' ),
( '1065', 'Govinda Reddy', 'Pantangi', '09-Feb-17', 'B2', 'Senior Technical Associate', 'Java Practice', 'CSC', 648, 'gpantangi@evoketechnologies.com', '12345' ),
( '1066', 'Uma Shankar Prudhvi', 'Raj Prasad Tiwari', '13-Feb-17', 'B1', 'Technical Associate', 'Java Practice', 'CSC', 134, 'utiwari@evoketechnologies.com', '12345' ),
( '1069', 'Bharath Kumar', 'Kapuraveni', '23-Feb-17', 'B2', 'Senior Technical Associate', 'Microsoft Practice', 'Clopay', 168, 'bkapuraveni@evoketechnologies.com', '12345' ),
( '1070', 'Mohammed Quasim', 'Iqbal', '24-Feb-17', 'B2', 'Senior Technical Associate', 'Java Practice', 'CSC', 756, 'miqbal@evoketechnologies.com', '12345' ),
( '1071', 'Ravi Kiran', 'Kandula', '16-Mar-17', 'B1', 'Software Test Engineer', 'QA Practice', 'CSC', 503, 'rkandula@evoketechnologies.com', '12345' ),
( '1072', 'Pooja', 'Berelliwar', '16-Mar-17', 'B2', 'Senior Software Test Engineer', 'QA Practice', 'CSC', 42, 'pberelliwar@evoketechnologies.com', '12345' ),
( '1073', 'Nageshwar Rao', 'Addanki', '20-Mar-17', 'B1', 'Technical Associate', 'Java Practice', 'CSC', 594, 'naddanki@evoketechnologies.com', '12345' ),
( '1074', 'Suri Babu', 'Batlanki', '20-Mar-17', 'B3', 'Technical Lead', 'Java Practice', 'Prime Tech', 1039, 'sbatlanki@evoketechnologies.com', '12345' ),
( '1075', 'Krishna', 'Laveti', '20-Mar-17', 'B2', 'Senior Technical Associate', 'BI Practice', 'CSC', 29, 'klaveti@evoketechnologies.com', '12345' ),
( '1076', 'Srujana', 'Tekmal', '20-Mar-17', 'B2', 'Senior Software Test Engineer', 'QA Practice', 'CSC', 2, 'stekmal@evoketechnologies.com', '12345' ),
( '1077', 'Gautam', 'Datta', '28-Mar-17', 'B1', 'Software Test Engineer', 'QA Practice', 'Clopay', 156, 'gdatta@evoketechnologies.com', '12345' ),
( '1078', 'Ramya', 'Yerram', '03-Apr-17', 'B1', 'Software Test Engineer', 'QA Practice', 'QA Practice', 507, 'ryerram@evoketechnologies.com', '12345' ),
( '1079', 'Jawahar Naveen', 'Yakkala', '03-Apr-17', 'B2', 'Senior Software Test Engineer', 'QA Practice', 'CSC', 658, 'nyakkala@evoketechnologies.com', '12345' ),
( '1080', 'Raja Sekhar', 'Karanam', '11-Apr-17', 'B1', 'Technical Associate', 'Java Practice', 'CSC', 648, 'rkaranam@evoketechnologies.com', '12345' ),
( '1081', 'Venkat Chandra', 'Eshwar Mungara', '13-Apr-17', 'B2', 'Senior Technical Associate', 'Microsoft Practice', 'Dominion', 546, 'vmungara@evoketechnologies.com', '12345' ),
( '1082', 'Swapna', 'Amrutha', '17-Apr-17', 'B2', 'Senior Executive Accounts', 'Finance', 'Accounts', 1, 'samrutha@evoketechnologies.com', '12345' ),
( '1083', 'Rajesh', 'Chaganti', '24-Apr-17', 'B2', 'Senior Technical Associate', 'Java Practice', 'CSC', 756, 'rchaganti@evoketechnologies.com', '12345' ),
( '1084', 'Rudra Pratap', 'Dalai', '27-Apr-17', 'A3', 'Trainee Technical Associate', 'Microsoft Practice', 'Clopay', 557, 'rdalai@evoketechnologies.com', '12345' ),
( '1085', 'Gajanan Anirudh', 'Shinde', '27-Apr-17', 'B1', 'Technical Associate', 'Microsoft Practice', 'CSC', 483, 'gshinde@evoketechnologies.com', '12345' ),
( '1086', 'H D S Siva Kumar', 'Pudi', '27-Apr-17', 'B2', 'Senior Technical Associate', 'Java Practice', 'CSC', 142, 'spudi@evoketechnologies.com', '12345' ),
( '1087', 'Pradeep Kumar', 'Pervela', '27-Apr-17', 'B2', 'Senior Technical Associate', 'Java Practice', 'Java Practice', 348, 'ppervela@evoketechnologies.com', '12345' ),
( '1088', 'Surendra Mohan', 'Juturu', '04-May-17', 'D1, Level 1', 'Associate Director', 'QA Practice', 'QA Practice', 880, 'sjuturu@evoketechnologies.com', '12345' ),
( '1089', 'Bhavani', 'Thota', '08-May-17', 'A3', 'Trainee Technical Associate', 'Big Data Practice', 'Big Data Practice', 1011, 'bthota@evoketechnologies.com', '12345' ),
( '1090', 'Sruthi', 'Gatta', '08-May-17', 'A3', 'Trainee Technical Associate', 'Big Data Practice', 'Big Data Practice', 1011, 'sgatta@evoketechnologies.com', '12345' ),
( '1091', 'Gautam', 'Singh', '08-May-17', 'A3', 'Trainee Technical Associate', 'Big Data Practice', 'Big Data Practice', 1011, 'gsingh@evoketechnologies.com', '12345' ),
( '1092', 'Arun', 'Talari', '11-May-17', 'C1', 'Business Development Manager', 'Sales', 'Inside Sales', 880, 'atalari@evoketechnologies.com', '12345' ),
( '1093', 'Shivakrishna', 'Modala', '11-May-17', 'B1', 'Technical Associate', 'Java Practice', 'CSC', 756, 'smodala@evoketechnologies.com', '12345' ),
( '1094', 'Manesh Varma', 'Penmetsa', '15-May-17', 'A3', 'Trainee Software Test Engineer', 'QA Practice', 'QA Practice', 507, 'mpenmetsa@evoketechnologies.com', '12345' ),
( '1095', 'Saikumar', 'Durgapu', '15-May-17', 'B1', 'Executive - Fraud Analyst', 'BPO', 'CSC', 571, 'sdurgapu@evoketechnologies.com', '12345' ),
( '1097', 'Vinay', 'Yellapu', '15-May-17', 'B2', 'Senior Software Test Engineer', 'BI Practice', 'CSC', 679, 'vyellapu@evoketechnologies.com', '12345' ),
( '1098', 'Varun Raj Yadav', 'Akula', '17-May-17', 'B2', 'Senior Technical Associate', 'Microsoft Practice', 'CSC', 483, 'vakula@evoketechnologies.com', '12345' ),
( '1099', 'Venkata Sunil', 'Badarla', '28-May-17', 'B2', 'Senior Software Test Engineer', 'QA Practice', 'Clopay', 521, 'vbadarla@evoketechnologies.com', '12345' ),
( '1101', 'Raja Ramesh', 'Chinta', '22-May-17', 'B2', 'Senior Technical Associate', 'Mobility Practice', 'Mobility Practice', 1119, 'rchinta@evoketechnologies.com', '12345' ),
( '1102', 'Pavan Kishore', 'Kancharla', '23-May-17', 'B2', 'Senior Technical Associate', 'Java Practice', 'CSC', 756, 'pkancharla@evoketechnologies.com', '12345' ),
( '1103', 'Satya Venkata Gowtham Raju', 'Pampana Purama', '29-May-17', 'B1', 'Technical Recruiter - US', 'Support Staff', 'Evoke', 866, 'spampana@evoketechnologies.com', '12345' ),
( '1104', 'Bhanu Charan', 'Purama', '01-Jun-17', 'B3', 'Lead – Business Development', 'Sales', 'Inside Sales', 348, 'bpurama@evoketechnologies.com', '12345' ),
( '1105', 'Amulya Bharath', 'Nagidi', '05-Jun-17', 'B2', 'Senior Technical Associate', 'BI Practice', 'CSC', 663, 'anagidi@evoketechnologies.com', '12345' ),
( '1106', 'Sai Kumar', 'Akula', '05-Jun-17', 'B1', 'Technical Associate', 'Big Data Practice', 'Big Data Practice', 1011, 'sakula@evoketechnologies.com', '12345' ),
( '1107', 'Lovaraju', 'Sakuru', '05-Jun-17', 'B2', 'Senior Technical Associate', 'Oracle Practice', 'CSC', 446, 'lsakuru@evoketechnologies.com', '12345' ),
( '1108', 'Peram', 'Phani Kumar', '08-Jun-17', 'B1', 'Technical Associate', 'Microsoft Practice', 'Clopay', 168, 'pperam@evoketechnologies.com', '12345' ),
( '1109', 'V R Krishna Chaitanya', 'Pakki', '12-Jun-17', 'B2', 'Senior Technical Associate', 'Mobility Practice', 'Axalta', 400, 'kpakki@evoketechnologies.com', '12345' ),
( '1110', 'Raghava Aditya', 'Kanumuri', '12-Jun-17', 'B2', 'Senior Software Test Engineer', 'QA Practice', 'CSC', 29, 'rkanumuri@evoketechnologies.com', '12345' ),
( '1111', 'Satish Kumar', 'Baisa', '19-Jun-17', 'B2', 'Senior Technical Associate', 'Java Practice', 'CSC', 658, 'sbaisa@evoketechnologies.com', '12345' ),
( '1112', 'Anusha', 'Addewar', '19-Jun-17', 'A2', 'Data Entry Associate', 'NA', 'CSC', 84, 'aaddewar@evoketechnologies.com', '12345' ),
( '1113', 'Vamshidhar', 'Podishetty', '22-Jun-17', 'A2', 'Data Entry Associate', 'NA', 'CSC', 84, 'vpodishetty@evoketechnologies.com', '12345' ),
( '1114', 'Karthik', 'Kavali', '22-Jun-17', 'B1', 'Executive - Fraud Analyst', 'BPO', 'CSC', 571, 'kkavali@evoketechnologies.com', '12345' ),
( '1115', 'Anupam Gourav', 'Patra', '26-Jun-17', 'B1', 'Technical Associate', 'Oracle Practice', 'CSC', 1056, 'apatra@evoketechnologies.com', '12345' ),
( '1116', 'Karthik', 'Gourishetty', '26-Jun-17', 'B1', 'Technical Associate', 'Big Data Practice', 'Big Data Practice', 1011, 'kgourishetty@evoketechnologies.com', '12345' ),
( '1117', 'Deepak Rao', 'Nethikar', '29-Jun-17', 'B1', 'Software Test Engineer', 'QA Practice', 'CSC', 134, 'dnethikar@evoketechnologies.com', '12345' ),
( '1118', 'Pavan Kumar', 'Vignesha Santosh Jonnalagadda', '29-Jun-17', 'B2', 'Senior Technical Associate', 'Java Practice', 'CSC', 756, 'pjonnalagadda@evoketechnologies.com', '12345' ),
( '1119', 'Nahid Ahmed', 'Mansuri', '29-Jun-17', 'B3', 'Technical Lead', 'Mobility Practice', 'Mobility Practice', 756, 'nmansuri@evoketechnologies.com', '12345' );
insert into projects (name)
values ('Non Billing (On Leave)');

